version: '3.9'
services:
  worker1:
    hostname: worker1
    container_name: worker1
    image: learn/dtf-multiworker-strategy:1.0.0
    environment:
      TF_CONFIG: "{
            \"cluster\": {
              \"chief\": [\"chief:2222\"],
              \"worker\": [\"worker1:2222\",\"worker2:2223\"]
            },
            \"task\": {\"type\": \"worker\", \"index\": 0}
          }"
    command: '/app/main.py'
  worker2:
    hostname: worker2
    container_name: worker2
    image: learn/dtf-multiworker-strategy:1.0.0
    environment:
      TF_CONFIG: "{
              \"cluster\": {
                \"chief\": [\"chief:2222\"],
                \"worker\": [\"worker1:2222\",\"worker2:2223\"]
              },
              \"task\": {\"type\": \"worker\", \"index\": 1}
            }"
    command: '/app/main.py'
  chief:
    hostname: chief
    container_name: chief
    image: learn/dtf-multiworker-strategy:1.0.0
    environment:
      TF_CONFIG: "{
            \"cluster\": {
              \"chief\": [\"chief:2222\"],
              \"worker\": [\"worker1:2222\",\"worker2:2223\"]
            },
            \"task\": {\"type\": \"chief\", \"index\": 0}
          }"
    command: '/app/main.py'